#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


exit 0


# npm run build

# git add dist

# isCommit=''

# for dir in $(git diff --name-only --cached);
# do 
#   if [[ $dir == "dist/"* ]]; then
#     isCommit=1
#     if [[ isCommit ]]; then
#       break
#     fi
#   fi
# done

# if [[ isCommit ]]; then
#   sh shell/build-push.sh
# fi